name: Build Bigdroid Project

on:
  push:
    tags:
      - '*'  # Triggers workflow on any tag push
  workflow_dispatch:  # Allows manual trigger

jobs:
  publish_release:
    runs-on: ubuntu-latest
    name: Building Bigdroid project
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Updated to latest version

      - name: Build Bigdroid
        uses: bigdroid/action-build@HEAD  # Use a stable version instead of HEAD
        env:
          API_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the secret is set in repo settings
