name: Build Bigdroid Project

on:
  push:
#     tags:
#       - '*'
#   workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    name: Building Bigdroid project
    steps:
      - uses: actions/checkout@v2
      
      - id: bigdroid-build
        uses: bigdroid/action-build@428003fc3d645522305416d32e52a0a562017252
        env:
            API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
