name: Install repo command

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install repo command
        run: |
          # Download repo from Google's storage
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo
          chmod a+x ~/bin/repo

          # Add the repo command to the PATH
          echo 'export PATH=~/bin:$PATH' >> ~/.bashrc
          source ~/.bashrc

      - name: Verify repo installation
        run: |
          repo --version  # Verify that repo is correctly installed

      # Continue with your other build steps here (sync repo, build, etc.)
