name: Build Bigdroid Project

on:
  push:
#     tags:
#       - '*'
#   workflow_dispatch:

jobs:
  publish_release:
    runs-on: ubuntu-latest
    name: Building Bigdroid project
    steps:
      - uses: actions/checkout@v2
      
      - id: bigdroid-build
#         uses: lhotari/action-upterm@v1
        uses: bigdroid/action-build@2c6c2197a1ab05cd5fca3f2fb7e710ea7a005de2
        env:
            API_TOKEN_GITHUB: ${{ secrets.GITHUB_TOKEN }}
