name: Install repo command

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install repo package
        run: |
          sudo apt-get update
          sudo apt-get install -y git-repo  # Install the repo package

      - name: Verify repo installation
        run: |
          repo --version  # Verify the repo command works

      # Add other steps here (like syncing the repo, building, etc.)
